// Ordenados por color para que la galería fluya: azules → acentos → cálidos.
// `height` es el alto de la captura a 720px de ancho (para el desplazamiento al pasar el mouse).
export const portfolio = [
  {
    slug: "solisimportsa",
    name: "Solis Import S.A.",
    url: "https://www.solisimportsa.com",
    domain: "solisimportsa.com",
    industry: "Insumos médicos",
    description: "Catálogo de equipos e insumos médico-quirúrgicos con líneas de producto por marca.",
    accent: "#2b8fd6",
    height: 1800,
  },
  {
    slug: "sige-pa",
    name: "SIGE ERP",
    url: "https://www.sige-pa.com/",
    domain: "sige-pa.com",
    industry: "Software empresarial",
    description: "Ecosistema ERP con ventas, inventario, contabilidad, planilla, CRM y facturación electrónica.",
    accent: "#1a8fe8",
    height: 1800,
  },
  {
    slug: "aduanabaloyes",
    name: "Aduana Baloyes",
    url: "https://aduanabaloyes.com",
    domain: "aduanabaloyes.com",
    industry: "Corredores de aduana",
    description: "Corredores de aduana desde 2007: permisos, valoración, cuarentena y exoneraciones con un equipo bilingüe.",
    accent: "#1f4a6b",
    height: 1800,
  },
  {
    slug: "cabanaselparador",
    name: "Cabañas El Parador",
    url: "https://cabanaselparador.com",
    domain: "cabanaselparador.com",
    industry: "Turismo y hospedaje",
    description: "Cabañas de montaña frente al Volcán Barú en Boquete, con café mirador y jardín panorámico.",
    accent: "#2f6b3a",
    height: 1800,
  },
  {
    slug: "gpsmarinepanama",
    name: "GPS Marine Panamá",
    url: "https://gpsmarinepanama.com",
    domain: "gpsmarinepanama.com",
    industry: "Industria marina",
    description: "Distribuidor autorizado Caterpillar: repuestos, motores y mantenimiento de embarcaciones.",
    accent: "#f2b705",
    height: 1800,
  },
  {
    slug: "aduanafdb",
    name: "Aduana FDB",
    url: "https://aduanafdb.com.pa",
    domain: "aduanafdb.com.pa",
    industry: "Logística y aduanas",
    description: "Corredor de aduana con servicios de exportación, importación y transporte de carga.",
    accent: "#ec9a13",
    height: 1800,
  },
  {
    slug: "alquileresymas",
    name: "Alquileres Eventos & Más",
    url: "https://alquileresymas.net",
    domain: "alquileresymas.net",
    industry: "Eventos",
    description: "Catálogo en línea de mobiliario y equipo para eventos con solicitud de cotización.",
    accent: "#8fb43a",
    height: 1800,
  },
  {
    slug: "elevadorescling",
    name: "Cling Company",
    url: "https://elevadorescling.com",
    domain: "elevadorescling.com",
    industry: "Mantenimiento de elevadores",
    description: "Mantenimiento preventivo y reparación de elevadores para edificios PH, con planes mensuales y soporte 24/7.",
    accent: "#b8924f",
    height: 1800,
  },
  {
    slug: "accabogados",
    name: "ACC Abogados",
    url: "https://accabogados.com.pa",
    domain: "accabogados.com.pa",
    industry: "Firma legal",
    description: "Firma de arbitraje internacional y derecho corporativo con blog y áreas de práctica.",
    accent: "#c8873a",
    height: 1800,
  },
  {
    slug: "werestauro",
    name: "WeRestauro",
    url: "https://werestauro.com",
    domain: "werestauro.com",
    industry: "Arquitectura y restauración",
    description: "Portafolio de proyectos de restauración patrimonial y museografía en tres países.",
    accent: "#d75e25",
    height: 1800,
  },
];
